### ISSUE TITLE
GNU Radio integration

### ISSUE THREAD

**Issue by fivitti** [gut-space/svarog#10]
GNU Radio has a lot of built-in, awesome tools for work with SDR.
Also exists [gr-satellites](https://github.com/daniestevez/gr-satellites) with ready GNU Radio blocks to reception data from satellites.
We should be able use this power. We need a possibility to use GNU Radio pipelines in our station.

**Comment by fivitti** [comment]
APT decoder may be implemented using GNU Radio blocks: [link](https://oz9aec.net/radios/gnu-radio/simple-apt-decoder-prototype). But it is primitive and doesn't include advanced processing as Doppler correction or NOAA telemetry decoding.

**Comment by fivitti** [comment]
Now, the reception recipes are shell scripts. It allow us to easily run standalone programs (as ```sox``` or ```noaa-apt```), but call Python modules (as GNU Radio) is harder. This way doesn't support re-use the code or follow good practices well. Shell scripts cannot return complex data.

We should analyze the possibility to organize the recipes as Python scripts.

**Comment by fivitti** [comment]
Now, our recipes realize schema:

### Input parameters

1. Prefix path. All path created by this script will be start with it
2. Frequency
3. Recording duration in seconds

### Output parameters

The output is print on standard output in format:
```
!! <TYPE>: "<PATH>"
```
where
    &lt;PATH&gt; is absolute path to file. Recipe IS NOT responsible for clean up this file.
    &lt;TYPE&gt; specify how product was saved. Now we used these types:

| Type   | Description |
| ---------- | --------------- |
| Signal   | WAV file with recorded signal after normalization |
| Product | PNG file with decoded imagery |

### Algorithm

All our recipes realize similar algorithm.

1. Record the signal - we use ```rtl_fm``` for it
2. Normalize the signal - using ```sox```
3. Decoding - in this step we run specialized tools different for each satellite
4. Clean up temporary files
5. Print to std out

### Notes

Advantages:

* Each recipe is isolated program - may be running without main station software
* Simple, easy to read and manual run for diagnostic purposes

Disadvantages

* Primitive logic
* Primitive exception handling
* Primitive output (useful messages are mixed with internal subprograms output)
* Non-testable
* Repeated code

**Comment by fivitti** [comment]
I propose to use [sh](https://github.com/amoffat/sh) library to call external programs.
It allow to execute process as call standard Python object methods. For example:

```python
from sh import ifconfig
print(ifconfig("eth0"))
```

We can use it to support ```rtl_fm```, ```sox```, ```noaa-apt```, ```metor-decode``` or ```meteor_demod``` without write additional code.

It is so much fancy, but it should allow to simplify recipes.

**Comment by fivitti** [comment]
GNU Radio developers prepare [PyBOMBS](https://github.com/gnuradio/pybombs/) utility. It allow to install dependencies from different package managers.

> PyBOMBS is good at building GNU Radio, UHD, and various Out of Tree (OOT) modules from source and then installing into a specified user directory rather than in the system files. PyBOMBS detects the user's Operating System and loads all of the prerequisites in the first stage of the build.

It is dedicated for install GNU Radio, but may be used to install another software too.
We can use it for install ```noaa-apt```, ```meteor-demod```, ```meteor-decode```, ```rtl_fm```(?) in ```setup.py``` file. Now installing dependencies for our station is complicated.

**Comment by tomaszmrugalski** [comment]
I've started looking at GNU Radio. [Here are my notes](https://github.com/gut-space/svarog/wiki/gr-ubuntu).

**Comment by tomaszmrugalski** [comment]
#50 integrated GR. We now have [GNU Radio based recipe for NOAA](https://github.com/gut-space/svarog/blob/master/station/recipes/noaa_apt_gr.py).
